/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vzbiljic.pki.plane;

import com.sun.istack.internal.NotNull;
import com.vzbiljic.pki.datasource.UserDataSource;
import com.vzbiljic.pki.plane.listadapter.IListAdapter;
import com.vzbiljic.pki.util.R;
import javax.swing.BoxLayout;

/**
 *
 * @author vzbiljic
 */
public class ListJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ListAgentsJPanel
     * 
     * @param adapter Adapter to initialize ListAdapter;
     * 
     */
    public ListJPanel(@NotNull IListAdapter adapter) {
        
        this.adapter = adapter;
        initComponents();
        onAfterInit();
    }
    
    public void repaintList(){
        jPanel1.removeAll();
        jPanel1.repaint();
        jPanel1.revalidate();
        
        fillList();
    }
    
    private void onAfterInit() {
        
        if(null == adapter){
            throw new RuntimeException("ListView adapter in null! Could not initialize main panel!");
        }
        jPanel1.setLayout(new BoxLayout(jPanel1,BoxLayout.Y_AXIS));
        
        fillList();
    }
    
    private void fillList(){
        adapter.fillList(jPanel1);
        
        jPanel1.repaint();
        jPanel1.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(252, 217, 217));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
    
    private IListAdapter adapter;
    
    
}
