/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vzbiljic.pki.plane;

import com.vzbiljic.pki.bean.User;
import com.vzbiljic.pki.datasource.UserDataSource;
import com.vzbiljic.pki.plane.listadapter.PropertyListAdapter;
import java.awt.event.ItemEvent;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;

/**
 *
 * @author vzbiljic
 */
public class ViewedByUserJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewedByUserJPanel
     */
    public ViewedByUserJPanel(String name, String telephone) {
        initComponents();
        initUserList();
        listVIewHolder.setVisible(false);
        userInfoPanel.setVisible(false);
        isAgent = false;
        onAffterInit(name,telephone);
    }
    
    public ViewedByUserJPanel(String name, String telephone, String agency) {
        initComponents();
        initUserList();
        listVIewHolder.setVisible(false);
        userInfoPanel.setVisible(false);
        isAgent = true;
        onAffterInit(name,telephone, agency);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userInfoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        telephone = new javax.swing.JLabel();
        agencyLabel = new javax.swing.JLabel();
        agency = new javax.swing.JLabel();
        listVIewHolder = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        userSelectList = new javax.swing.JComboBox<>();

        setBackground(java.awt.Color.white);

        userInfoPanel.setBackground(com.vzbiljic.pki.util.R.color.ACCENT);

        jLabel1.setText("Korisnik:");

        jLabel2.setText("Telefon:");

        user.setText("Branko");

        telephone.setText("0631234567");

        agencyLabel.setText("Agencija:");

        agency.setText("BGSport");

        javax.swing.GroupLayout userInfoPanelLayout = new javax.swing.GroupLayout(userInfoPanel);
        userInfoPanel.setLayout(userInfoPanelLayout);
        userInfoPanelLayout.setHorizontalGroup(
            userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(agencyLabel)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user)
                    .addComponent(telephone)
                    .addComponent(agency))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userInfoPanelLayout.setVerticalGroup(
            userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(user))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agencyLabel)
                    .addComponent(agency))
                .addGap(11, 11, 11)
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(telephone))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listVIewHolder.setBackground(java.awt.Color.white);
        listVIewHolder.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(com.vzbiljic.pki.util.R.color.ACCENT);

        jLabel3.setText("Korisnik:");

        userSelectList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        userSelectList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                userSelectListItemStateChanged(evt);
            }
        });
        userSelectList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSelectListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userSelectList, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(userSelectList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listVIewHolder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listVIewHolder, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userSelectListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_userSelectListItemStateChanged
         if (evt.getStateChange() == ItemEvent.SELECTED) {
            String item = (String)evt.getItem();
            User u = null;
          
            for (int i = 0; i < UserDataSource.getInstance().size(); i++) {
                if(item.equals(UserDataSource.getInstance().get(i).getUsername())){
                    u = UserDataSource.getInstance().get(i);
                    break;
                }
            }
            if(null != u){
                userInfoPanel.setVisible(true);
                listVIewHolder.setVisible(true);
                
                listVIewHolder.revalidate();
                if(isAgent){
                    agency.setVisible(true);
                    agencyLabel.setVisible(true);
                }
                onAffterInit(u.getUsername(),u.getTelephone(),u.getAgency());
            }
          
       }
    }//GEN-LAST:event_userSelectListItemStateChanged

    private void userSelectListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSelectListActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_userSelectListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agency;
    private javax.swing.JLabel agencyLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel listVIewHolder;
    private javax.swing.JLabel telephone;
    private javax.swing.JLabel user;
    private javax.swing.JPanel userInfoPanel;
    private javax.swing.JComboBox<String> userSelectList;
    // End of variables declaration//GEN-END:variables

    private void onAffterInit(String name, String telephone) {
        agencyLabel.setVisible(false);
        agency.setVisible(false);
        
        user.setText(name);
        
        userInfoPanel.revalidate();
        userInfoPanel.repaint();
        
        this.telephone.setText(telephone);
        listVIewHolder.add(new ListJPanel(new PropertyListAdapter()));
        
        listVIewHolder.revalidate();
        listVIewHolder.repaint();
        
    }
    
    private void initUserList(){
        userSelectList.setModel(new DefaultComboBoxModel<String>(UserDataSource.getInstance().getDescription()));
        
    }

    private void onAffterInit(String name, String telephone, String agency) {
        user.setText(name);
        this.agency.setText(agency);
        this.telephone.setText(telephone);
        listVIewHolder.add(new ListJPanel(new PropertyListAdapter()));
        
        listVIewHolder.revalidate();
        listVIewHolder.repaint();
    }
    
    private boolean isAgent;
}
