/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vzbiljic.pki.plane.model;

import com.vzbiljic.pki.util.Util;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import org.jcp.xml.dsig.internal.dom.Utils;

/**
 *
 * @author vzbiljic
 */
public class PropertiesListJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PropertiesListJPanel
     */
    public PropertiesListJPanel(String imgPath, String price, String address) {
        initComponents();
        onAfterInit(imgPath,price,address);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        delete = new javax.swing.JButton();

        setBackground(com.vzbiljic.pki.util.R.color.ACCENT);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawable/mm.jpg"))); // NOI18N
        image.setToolTipText("");

        price.setText("cena: 500$");

        address.setText("Milutina Milankovica 84");

        delete.setForeground(com.vzbiljic.pki.util.R.color.RED);
        delete.setText("Obriši");
        delete.setBorderPainted(false);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(price))
                    .addComponent(address))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delete)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(price)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(address)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JButton delete;
    private javax.swing.JLabel image;
    private javax.swing.JLabel price;
    // End of variables declaration//GEN-END:variables

    private void onAfterInit(String imgPath, String price, String address) {
        try {
            Image icon = ImageIO.read(getClass().getResource(imgPath));
            
            icon = Util.scaleImage(icon,121,80);
            
            this.image.setIcon(new ImageIcon(icon));
            
            this.address.setText(address);
            
            this.price.setText("Cena:" + price);
            
        } catch (IOException ex) {
            Logger.getLogger(PropertiesListJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
}
